# Arquivo para criar conexão entre o PHP e Mysql
version: '3'

services:
  web:
    build:
      context: .
    ports:
      - "8000:80"
    depends_on:
      - db
    volumes:
      - ./:/var/www/html
      - ./apache/vhost.conf:/etc/apache2/sites-available/000-default.conf

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog_db
      MYSQL_USER: blog_user
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
