<?php

use Jonashcr\Admin\Users\User;

include(ADMIN_VIEW . '/components/header.phtml') ?>

<h2>Lista de Posts</h2>

<?php if (User::$role == 'Admin') : ?>
    <a class="btn btn-primary" href="/admin/posts?action=createForm">Novo Post</a>
<?php endif ?>

<?php if (!empty($_SESSION['error'])) : ?>
    <div class="text-danger">
        <p><?= $_SESSION['error'] ?></p>
    </div>
<?php endif ?>

<table border="1" style="width: 95%;margin: 0 19px;">
    <tr>
        <td>ID</td>
        <td>Título</td>
        <td>URL</td>
        <td>Status</td>
        <td>Criado em</td>
        <td>Atualizado em</td>
        <td>Ação</td>
    </tr>
    <?php foreach ($posts as $post) : ?>
        <tr>
            <td><?= $post['id']; ?></td>
            <td><?= $post['title']; ?></td>
            <td><?= $post['slug']; ?></td>
            <td><?= $post['status']; ?></td>
            <td><?= $post['created_at']; ?></td>
            <td><?= $post['updated_at']; ?></td>
            <?php if (User::$role == 'Admin') : ?>
                <td>
                    <a class="btn btn-secondary" href="/admin/posts?action=edit&id=<?= $post['id']; ?>">Editar</a>
                    <form action="/admin/posts?action=delete" method="post">
                        <input type="hidden" name="id" value="<?= $post['id']; ?>">
                        <button type="submit" class="btn btn-danger" onclick="return confirm('Deseja excluir este post?')">Excluir</button>
                    </form>
                </td>
            <?php endif ?>
        </tr>
    <?php endforeach; ?>
</table>

<?php include(ADMIN_VIEW . '/components/footer.phtml') ?>