<?php
$isEdit = isset($user);
?>

<?php if ($isEdit): ?>
    <input type="hidden" name="id" value="<?= $user['id']; ?>">
<?php endif; ?>

<div class="mb-3">
    <label for="username">Nome:</label>
    <input type="text" id="username" name="username" value="<?= $isEdit ? $user['username'] : '' ?>" required>
</div>

<div class="mb-3">
    <label for="email">Email:</label>
    <input type="email" id="email" name="email" value="<?= $isEdit ? $user['email'] : '' ?>" required>
</div>

<div class="mb-3">
    <label for="role">Permissão</label>
    <select name="role" id="role">
        <option value="Admin" <?= $user['role'] == 'Admin' ? 'selected' : '' ?> >Administrativo</option>
        <option value="Visitor" <?= $user['role'] == 'Visitor' ? 'selected' : '' ?>>Visitante</option>
    </select>
</div>

<?php if (!$isEdit) : ?>
    <div class="mb-3">
        <label for="password">Senha:</label>
        <input type="password" id="password" name="password" required>
    </div>
<?php endif; ?>