<?php include('components/header.phtml') ?>

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    Bem-vindo ao Admin
                </div>
                <div class="card-body">
                    <p>Você está logado como 
                        ADmin
                    </p>
                    <a href="logout.php" class="btn btn-danger">Logout</a>
                </div>
            </div>
        </div>
    </div>
</div>

<?php include('components/footer.phtml') ?>
