<footer style="position: fixed; bottom: 0; width: 100%;  padding: 10px; text-align: center;">
    <img src="/src/admin/view/static/assets/my-profile.jpeg" alt="Minha Foto" style="width: 50px; height: 50px; border-radius: 50%; margin-right: 10px;">
    <a href="https://www.linkedin.com/in/jonas-henrique-castro-rodrigues-7b5241158/" target="_blank">Desenvolvido por Jonas Henrique Castro Rodrigues.</a>
</footer>