<footer class="bg-dark text-light text-center py-4">
    <div class="container">
        <div class="row">
            <div class="col-md-9 position-relative" style="left: 15%;">
                <img src="/src/admin/view/static/assets/my-profile.jpeg" alt="Minha Foto" class="img-fluid rounded-circle" width="50">
                <p class="mb-1">Desenvolvido por <a href="https://www.linkedin.com/in/jonas-henrique-castro-rodrigues-7b5241158/" class="text-light" target="_blank">Jonas Henrique Castro Rodrigues</a></p>
            </div>
        </div>
    </div>
</footer>
